CREATE TABLE `block` (
  `block_pk` INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
  `block_name` VARCHAR(255) NOT NULL,
  `block_weight` INT UNSIGNED NOT NULL,
  `block_count` INT UNSIGNED NOT NULL DEFAULT 1,
  `course_fk` INT UNSIGNED DEFAULT NULL,
  `entries` JSON DEFAULT NULL,
  `dt_created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`block_pk`),
  CONSTRAINT `FK_block_course` FOREIGN KEY (`course_fk`) REFERENCES `course` (`course_pk`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;