CREATE TABLE `term` (
  `term_pk` INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
  `term_name` VARCHAR(255) NOT NULL UNIQUE,
  `dt_created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`term_pk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;